const countries = [
    {
        key: 0,
        country: "/img/homepage/brazil-.png",
        name: "Brazil",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 1,
        country: "/img/homepage/united-states.png",
        name: "English",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {   
        key: 2,
        country: "/img/homepage/flag(3).png",
        name: "Spain",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 3,
        country: "/img/homepage/france.png",
        name: "French",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 4,
        country: "/img/homepage/italy.png",
        name: "Italian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 5,
        country: "/img/homepage/hungary.png",
        name: "Hungarian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 6,
        country: "/img/homepage/ukraine.png",
        name: "Ukranian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 7,
        country: "/img/homepage/russia.png",
        name: "Russian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",

    },
    {
        key: 8,
        country: "/img/homepage/poland.png",
        name: "Poland",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 9,
        country: "/img/homepage/germany.png",
        name: "German",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 10,
        country: "/img/homepage/netherlands.png",
        name: "Dutch",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 11,
        country: "/img/homepage/greece.png",
        name: "Greek",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 12,
        country: "/img/homepage/norway.png",
        name: "Norwegian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 13,
        country: "/img/homepage/denamark.png",
        name: "Danish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 14,
        country: "/img/homepage/saudi-arabia.png",
        name: "Arabic",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 15,
        country: "/img/homepage/turkey.png",
        name: "Turkish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 16,
        country: "/img/homepage/china.png",
        name: "Chinese",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
        
    },
    {
        key: 17,
        country: "/img/homepage/japan.png",
        name: "Japanese",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "8TH",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
]

export default countries;